Retry reading when file is locked
logdna/logdna-agent pull request #171
Opened 2020-05-01 21:19 UTC by summatix

https://github.com/logdna/logdna-agent/issues/167

This fixes a bug in the Windows version when applications have the file open and obtain a lock. The solution is simply to wait until the process has released the lock and read again.

I've tested this and the logs are showing up currently in LogDNA.

2020-10-07 19:50 UTC, smusali requested changes
Thanks for the PR, @summatix! Can you please remove the semi-colons from your changes?

![image](https://user-images.githubusercontent.com/34287490/95380502-d6741780-08b4-11eb-830c-f2d47ead854c.png)

Thanks!

2020-10-08 21:10 UTC, darinspivey commented
@summatix it's also worth noting that the underlying `TailReadStream` will be replaced soon by some new code that we authored.  When its initial version is merged into the main branch, we will certainly add this support to it (and share it with you and the world, of course!)  A constructor option that takes a "rery" list of codes and/or messages would keep it easy to use and generic.  Standby!

2020-10-15 20:56 UTC, smusali approved these changes

2020-10-15 21:06 UTC, smusali commented
Done in [here](https://github.com/logdna/logdna-agent/pull/208/commits/e4a2d6caf2cf26098343d27f2017b71eb952959c)

2020-10-15 21:06 UTC, closed without merging